all:
	gcc-4.4 -g -Wall -o MineAndBuild.x86_64 \
		`sdl-config --cflags --libs` -lSDL_image \
		main.c \
		MineList.c \
		MineEngine.c \
		MineEvent.c \
		MineFont.c \
		MineGame.c \
		MineCamera.c \
		MineScrollCamera.c \
		MinePlayerCamera.c \
		MineBlock.c \
		Blocks/MineNoneBlock.c \
		Blocks/MineDirtBlock.c \
		Blocks/MineStoneBlock.c \
		MineWorld.c \
		MineWorldGenerator.c \
		MineState.c \
		States/MineTestState.c \
		MineObject.c \
		MineController.c \
		MinePlayerController.c

