all:
	gcc-4.4 -g -Wall -o MineAndBuild.x86_64 \
		`sdl-config --cflags --libs` -lSDL_image \
		main.c \
		MineList.c \
		MineEngine.c \
		MineEvent.c \
		MineFont.c \
		MineGame.c \
		MineCamera.c \
		MineScrollCamera.c \
		MineState.c \
		States/MineTestState.c

